### ISSUE TITLE
Listening For JoinGame Packet Cause Join Error

### ISSUE THREAD

**Issue by Xuwznln** [Exceptionflug/protocolize#109]
**Describe the bug**
I want to read the worlds info sent from the server. After reading https://wiki.vg/Protocol, I found it possible to read JoinGame Packet. So I tried to register a custom packet and read&write like Login.class do in BungeeCord. But the client got this following error.
Exception Connecting:QuietException : Unexpected packet received during server login process!
0e0100

**Proxy environment**
BungeeCord

**Minecraft versions used**
1.18

**Comment by Exceptionflug** [comment]
Hey, since BungeeCord already implements the JoinGame packet, you don't have to (and also can't) implement your own version of this packet. In order to work with the packet you have to add `bungeecord-protocol` as a dependency to your project. Then you can listen to the `Login` packet using the packet listener.

**Comment by Xuwznln** [comment]
Yeah, I tried that and succeeded. Thanks for your help!
