### ISSUE TITLE
Cancelling Sign Usage - Getting ItemStack in BlockPlacement

### ISSUE THREAD

**Issue by A248** [Exceptionflug/protocolize#23]
**My objective**
Block specific players from using signs. Ideally, they should not be able to edit signs at all, but still be able to place them.

**Questions**

1. Will support be added for a SignChange packet or similar?
2. _If not_, I will have to use the BlockPlacement packet. How can I retrieve the type of block from a BlockPlacement packet?

**Current Conundrum**
Right now, I am trying to work with BlockPlacement packet but I cannot seem to find a safe way to retrieve the type of block placed. BlockPlacement#getItemStack is deprecated, and it seems from the source that it is also non-functional.

Here is what I have so far.
``` java
public class SignInterceptor extends PacketAdapter<BlockPlacement> {

	public SignInterceptor() {
		super(Stream.UPSTREAM, BlockPlacement.class);
	}

	@Override
	public void receive(PacketReceiveEvent<BlockPlacement> evt) {
		if (!evt.getPacket().isCancelSend()) {
			if (false) { // check if placed block is a sign
				evt.getPacket().setCancelSend(true);
				evt.getPlayer().sendMessage(new TextComponent("You may not place signs!"));
			}
		}
	}
}
```

**Last Notes**
* I have checked closed issues but none seem relevant to this one.
* I was unable to find an issue format, so I apologise in advance in case I should have used a different formatting style.

**Comment by A248** [comment]
This issue should get the probably `question` label.

**Comment by Exceptionflug** [comment]
Hey thank you for using Protocolize!

**To your question number one:**

You can simply add support for custom packets at your own. There are simple things you need:

1. A map containing every protocol id and the packet's according packet id from that version. Example [click here](https://github.com/Exceptionflug/protocolize/blob/master/protocolize-items/src/main/java/de/exceptionflug/protocolize/items/packet/BlockPlacement.java#L20).
2. A class extending the `de.exceptionflug.protocolize.api.protocol.AbstractPacket` class. For example [click here](https://github.com/Exceptionflug/protocolize/blob/master/protocolize-items/src/main/java/de/exceptionflug/protocolize/items/packet/BlockPlacement.java).
3. Documentation about the packet layout for all supported protocol versions. For sign change this would be the link for the 1.14.4 protocol: https://wiki.vg/Protocol#Update_Sign
You can find documentation for older protocol versions right here: https://wiki.vg/Protocol_version_numbers
4. In the class you have to override the `read(ByteBuf buf, Direction direction, int protocolVersion)` and `write(ByteBuf buf, Direction direction, int protocolVersion)` methods. Take a look at other protocolize pre-implemented packets like [BlockPlacement](https://github.com/Exceptionflug/protocolize/blob/master/protocolize-items/src/main/java/de/exceptionflug/protocolize/items/packet/BlockPlacement.java).
5. Register the packet using `ProtocolAPI.getPacketRegistration().registerPacket(Protocol protocol, Direction direction, Class<? extends AbstractPacket> clazz, Map<Integer, Integer> protocolIdMapping);`. For example [click here](https://github.com/Exceptionflug/protocolize/blob/master/protocolize-items/src/main/java/de/exceptionflug/protocolize/items/ItemsModule.java#L19).
That's all. Now you can use your own implemented packet like the others.

**To your second question:**

This is not possible since this requires experimental features to be enabled **which I don't recommend.** Protocolize is not able to track the spigot inventory contents when those experimental features are disabled. The only recommended way is the way stated above. Otherwise you could have accessed the PlayerInventory using `InventoryManager.getInventory(UUID uuid);` and get the item from the held item slot. 

For further questions I am ready to help :)

**Comment by Exceptionflug** [comment]
Another thing I have to mention: Please don't use `AbstractPacket.setCancelSend(boolean cancelSend);` anymore. Please cancel the event itself instead :)

**Comment by Exceptionflug** [comment]
fbdd5a2e20e101100ab78b5a7f85c466eea32012

**Comment by Exceptionflug** [comment]
https://github.com/Exceptionflug/protocolize/commit/fbdd5a2e20e101100ab78b5a7f85c466eea32012

**Comment by Exceptionflug** [comment]
In https://github.com/Exceptionflug/protocolize/commit/fbdd5a2e20e101100ab78b5a7f85c466eea32012 you will find an implementation of SignUpdate coming to the next major protocolize release supporting 1.15 next week.

**Comment by A248** [comment]
Thank you! I honestly didn't expect this feature to be added so quickly.

You certainly know much more than I do about packets. I doubt I could implement a sign-change packet myself. However, I'm glad you are able and willing :)

**Comment by Exceptionflug** [comment]
No problem. You can use an early version of v1.5.0 by cloning and building the 1.15 branch. Artifact is deployed to maven repo.

**Comment by A248** [comment]
Don't worry, I was competent enough to figure that out myself using maven dependency resolution.

**Comment by A248** [comment]
SignUpdate packet now added to master branch courtesy of Exceptionflug. https://github.com/Exceptionflug/protocolize/blob/master/protocolize-world/src/main/java/de/exceptionflug/protocolize/world/packet/SignUpdate.java
