### ISSUE TITLE
Exception occurred when reading ItemStack from buffer. Protocol version = 736

### ISSUE THREAD

**Issue by Stixil** [Exceptionflug/protocolize#54]
Here is a stacktrace: https://mcpaste.io/2f05224fd3174933

**Comment by Exceptionflug** [comment]
Hey,

please tell me more about this exception. When does this occur?

**Comment by Stixil** [comment]
Hi, it happens all the time. It spams the console almost constantly.

**Comment by Exceptionflug** [comment]
Please be sure you are running the latest version of official BungeeCord or Waterfall and don't use other protocol manipulation Software (ViaVersion, ProtocolSupport etc.). If you do so, please try to disable them and test if the error still occurrs.

**Comment by Prouser123** [comment]
> Hi, it happens all the time. It spams the console almost constantly.

(filling in for Stixil) - We're using the latest version of both Waterfall and Paper. No other protocol software is used on the proxy, although ProtocolSupport is on the paper server since 1.16.2 is not natively supported yet. However, there are no errors in the paper console and the server does not crash or exhibit anything.

We've also discovered that crafting on 1.16.2 crashes the Waterfall server entirely. It floods the consoe with the error message linked above and the server crashes. Unfortunately the console is so overwhelmed with these messages during the crash that no other messages are visible.

**Comment by Exceptionflug** [comment]
Here is a debug build which helps me to find the problem. Please send me a log file when you are using it: https://img.exceptionflug.de/protocolize-plugin.jar

**Comment by Stixil** [comment]
Thank you, I will be testing it right away.

**Comment by Exceptionflug** [comment]
Any results?
